# .github/workflows/build-ee.yml

name: Build and Push Ansible Execution Environment
# This section defines when the pipeline should run.
on:
  # Run automatically every time code is pushed to the 'main' branch.
  push:
    branches: [ "main" ]
  # Allows you to manually trigger the pipeline from the GitHub Actions UI.
  workflow_dispatch:

jobs:
  build-and-push-ee:
    # Use the latest version of Ubuntu for our runner environment.
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare Image Name and Tags
        id: prep
        run: |
          echo "IMAGE_FULL_NAME=${{ vars.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "TAG_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
  
      # Step 3: Install ansible-builder
      # Install the necessary tool to build our EE.
      - name: Install ansible-builder
        run: pip install ansible-builder
      # This uses the secrets you configured in GitHub repository settings.
      - name: Log in to Red Hat Registry
        # uses: docker/login-action@v3
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_SA_USERNAME }}
          password: ${{ secrets.REDHAT_SA_PASSWORD }}

      # Step 6: Log in to Quay.io
      - name: Log in to Quay.io
        # uses: docker/login-action@v3
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build EE with ansible-builder
        run: |
          echo "INFO: Building Execution Environment with tag: ${{ env.TAG_SHA }}"
          ansible-builder build \
            --tag quay.io/${{ env.IMAGE_FULL_NAME }}:${{ env.TAG_SHA }} \
            --context . \
            --container-runtime podman

      - name: Push the EE image to the registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_FULL_NAME }}
          tags: ${{ env.TAG_SHA }}
          registry: quay.io/${{ secrets.QUAY_USER }}
